name: Deploy PoC Mixed Environment

on:
  push:
    branches: [ devv ]

jobs:
  deploy-poc:
    runs-on: self-hosted
    environment: PoC
    steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          # DÉPLOIEMENT PKI
          - name: Deploy to PKI
            uses: appleboy/scp-action@master
            with:
              host: ${{ secrets.HOST_PKI }}
              username: "pki"
              key: ${{ secrets.SSH_PKI }}
              source: "pki/ca.py"
              target: "~"
              strip_components: 1
    
          # DÉPLOIEMENT BOB
          - name: Deploy to Bob
            uses: appleboy/scp-action@master
            with:
              host: ${{ secrets.HOST_BOB }}
              username: "bob"
              key: ${{ secrets.SSH_BOB }}
              # On prend tout sauf pki et le client
              source: "net, sec, serverB.py "
              target: "PQC/"
    
          # DÉPLOIEMENT ALICE
          - name: Deploy to Alice
            uses: appleboy/scp-action@master
            with:
              host: ${{ secrets.HOST_ALICE }}
              username: "alice"
              key: ${{ secrets.SSH_ALICE }}
              # On prend tout sauf pki et le serveur
              source: "net, sec, clientA.py "
              target: "PQC/"
