name: Deploy PoC Mixed Environment

on:
  push:
    branches: [ main ]

jobs:
  deploy-poc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Déploiement sur la machine PKI (Uniquement ca.py)
      - name: Deploy to PKI
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_PKI }}
          username: "pki"
          key: ${{ secrets.SSH_PKI }}
          source: "pki/ca.py"
          target: "~"
          strip_component: 1

      # 2. Déploiement sur le SERVER BOB (Tout sauf ca.py)
      - name: Deploy to Bob (Server)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_BOB }}
          username: "bob"
          key: ${{ secrets.SSH_BOB }}
          # On exclut ca.py et les dossiers git
          # rm: true # Optionnel : nettoie le dossier cible avant
          source: "*, !pki , !clientA.py , !*.git" 
          target: "PQC/"

      # 3. Déploiement sur le CLIENT ALICE (Tout sauf ca.py)
      - name: Deploy to Alice (Client)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_ALICE }}
          username: "alice"
          key: ${{ secrets.SSH_ALICE }}
          source: "*, !pki , !serverB.py , !*.git" 
          target: "PQC/"

