name: Deploy PoC Mixed Environment

on:
  push:
    branches: [ main ]

jobs:
  deploy-poc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to PKI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PKI }}
          username: pki
          key: ${{ secrets.SSH_PKI }}
          script: |
            scp -r ${{ github.workspace }}/pki/ca.py ~

      - name: Deploy to Bob (Server)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_BOB }}
          username: bob
          key: ${{ secrets.SSH_BOB }}
          script: |
            mkdir -p ~/PQC
            scp -r ${{ github.workspace }}/* ~/PQC/ \
              --exclude='pki' \
              --exclude='clientA.py' \
              --exclude='.git'

      - name: Deploy to Alice (Client)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ALICE }}
          username: alice
          key: ${{ secrets.SSH_ALICE }}
          script: |
            mkdir -p ~/PQC
            scp -r ${{ github.workspace }}/* ~/PQC/ \
              --exclude='pki' \
              --exclude='serverB.py' \
              --exclude='.git'
